// 隐私政策 — 14 语言 | 更新：2026-10-05 | 新增无广告声明
const POLICIES = {};

POLICIES["zh-Hans"] = `<h1>魔方马赛克 — 隐私政策</h1><p class="date">最后更新：2026年10月5日</p><h2>概述 <span class="badge green">100% 离线</span> <span class="badge blue">无广告</span></h2><p>魔方马赛克是一款完全离线的图片隐私保护工具。我们<b style="color:#2e7d32">不收集、不存储、不上传</b>任何用户数据。</p><h2>无广告承诺</h2><p><b style="color:#1565c0">本应用永久无广告、无弹窗、无推送。</b>我们不集成任何广告 SDK，不展示任何第三方推广内容，也不会通过任何形式向您发送营销信息。应用的全部收入来自一次性购买费用，我们没有任何动机去追踪您或向您展示广告。</p><h2>我们收集什么</h2><p><b style="color:#2e7d32">什么都不收集。</b>零网络请求、零第三方 SDK、零数据收集。</p><h2>图片数据处理</h2><ul><li>所有识别和打码处理均在设备本地完成</li><li>处理结果仅保存在您的设备上</li><li>导出自动清除 EXIF/GPS 等元数据</li></ul><h2>权限说明</h2><ul><li><b>相册读取</b>：浏览并选择要打码的照片。仅读取您选择的照片，不扫描不上传。</li><li><b>相册写入</b>：保存打码后的图片。保存新副本，不覆盖原图。</li></ul><h2>联系我们</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["zh-Hant"] = `<h1>魔方馬賽克 — 隱私政策</h1><p class="date">最後更新：2026年10月5日</p><h2>概述 <span class="badge green">100% 離線</span> <span class="badge blue">無廣告</span></h2><p>魔方馬賽克是一款完全離線的圖片隱私保護工具。我們<b style="color:#2e7d32">不收集、不儲存、不上傳</b>任何使用者資料。</p><h2>無廣告承諾</h2><p><b style="color:#1565c0">本應用永久無廣告、無彈出、無推播。</b>我們不整合任何廣告 SDK，不顯示任何第三方推廣內容，也不會透過任何形式向您發送行銷資訊。應用的全部收入來自一次性購買費用。</p><h2>我們收集什麼</h2><p><b style="color:#2e7d32">什麼都不收集。</b>零網路請求、零第三方 SDK、零資料收集。</p><h2>圖片處理</h2><ul><li>所有識別和打碼均在裝置本地完成</li><li>結果僅保存在裝置上</li><li>匯出自動清除 EXIF/GPS</li></ul><h2>權限</h2><ul><li><b>相簿讀取</b>：瀏覽並選擇照片。僅讀取所選照片。</li><li><b>相簿寫入</b>：儲存處理後圖片。新副本，不覆蓋原圖。</li></ul><h2>聯絡我們</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["en"] = `<h1>MosaicMagic — Privacy Policy</h1><p class="date">Last updated: October 5, 2026</p><h2>Overview <span class="badge green">100% Offline</span> <span class="badge blue">Ad-Free</span></h2><p>MosaicMagic is a fully offline photo privacy tool. We <b style="color:#2e7d32">do not collect, store, or upload</b> any user data.</p><h2>No-Ads Commitment</h2><p><b style="color:#1565c0">This app is permanently ad-free.</b> No ads, no pop-ups, no push notifications. We integrate zero advertising SDKs, display zero third-party promotional content, and will never send you marketing messages. Our sole revenue is the one-time purchase price — we have zero incentive to track you or show you ads.</p><h2>What We Collect</h2><p><b style="color:#2e7d32">Nothing.</b> Zero network requests. Zero third-party SDKs. Zero data collection.</p><h2>Image Processing</h2><ul><li>All detection and censoring happens locally</li><li>Results stored only on your device</li><li>Exports automatically strip EXIF/GPS metadata</li></ul><h2>Permissions</h2><ul><li><b>Photo Read</b>: Browse and select photos. Only accesses photos you choose.</li><li><b>Photo Write</b>: Save censored images. New copy — originals untouched.</li></ul><h2>Contact</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["ja"] = `<h1>モザイクマジック — プライバシーポリシー</h1><p class="date">最終更新：2026年10月5日</p><h2>概要 <span class="badge green">100% オフライン</span> <span class="badge blue">広告なし</span></h2><p>モザイクマジックは完全オフラインの写真プライバシー保護ツールです。<b style="color:#2e7d32">収集・保存・アップロードは一切行いません。</b></p><h2>広告なしの約束</h2><p><b style="color:#1565c0">本アプリは永久に広告なし。</b>広告SDKゼロ、ポップアップゼロ、プッシュ通知ゼロ。マーケティングメッセージも送信しません。収益は買い切り購入のみ。</p><h2>収集データ</h2><p><b style="color:#2e7d32">なし。</b>ネットワーク通信ゼロ、SDKゼロ、データ収集ゼロ。</p><h2>画像処理</h2><ul><li>すべて端末内で処理</li><li>結果は端末内にのみ保存</li><li>書き出し時EXIF/GPS自動削除</li></ul><h2>権限</h2><ul><li><b>写真読み取り</b>：閲覧・選択のみ</li><li><b>写真書き込み</b>：新規コピー保存、元画像不改変</li></ul><h2>お問い合わせ</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["ko"] = `<h1>모자이크 매직 — 개인정보 처리방침</h1><p class="date">최종 업데이트: 2026년 10월 5일</p><h2>개요 <span class="badge green">100% 오프라인</span> <span class="badge blue">광고 없음</span></h2><p>모자이크 매직은 완전 오프라인 사진 개인정보 보호 도구입니다. <b style="color:#2e7d32">수집·저장·업로드를 하지 않습니다.</b></p><h2>광고 없음 약속</h2><p><b style="color:#1565c0">이 앱은 영구적으로 광고가 없습니다.</b> 광고 SDK 없음, 팝업 없음, 푸시 알림 없음. 마케팅 메시지도 보내지 않습니다. 수익은 일회성 구매만.</p><h2>수집 데이터</h2><p><b style="color:#2e7d32">없음.</b> 네트워크 요청 없음, SDK 없음, 데이터 수집 없음.</p><h2>이미지 처리</h2><ul><li>모든 처리는 기기 내에서</li><li>결과는 기기에만 저장</li><li>내보낼 때 EXIF/GPS 자동 삭제</li></ul><h2>권한</h2><ul><li><b>사진 읽기</b>: 선택한 사진만</li><li><b>사진 쓰기</b>: 새 복사본, 원본 수정 안 함</li></ul><h2>연락처</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["ar"] = `<h1>موزاييك ماجيك — سياسة الخصوصية</h1><p class="date">آخر تحديث: 5 أكتوبر 2026</p><h2>نظرة عامة <span class="badge green">100% دون اتصال</span> <span class="badge blue">بدون إعلانات</span></h2><p>موزاييك ماجيك أداة حماية خصوصية الصور تعمل دون اتصال. <b style="color:#2e7d32">لا نجمع أو نخزن أو نرفع</b> أي بيانات.</p><h2>التزام بدون إعلانات</h2><p><b style="color:#1565c0">هذا التطبيق خالٍ من الإعلانات نهائياً.</b> لا إعلانات، لا نوافذ منبثقة، لا إشعارات تسويقية. مصدر الدخل هو الشراء لمرة واحدة فقط.</p><h2>ما نجمعه</h2><p><b style="color:#2e7d32">لا شيء.</b> صفر طلبات شبكة، صفر SDK، صفر جمع بيانات.</p><h2>معالجة الصور</h2><ul><li>جميع المعالجة على جهازك</li><li>النتائج على جهازك فقط</li><li>حذف تلقائي لـ EXIF/GPS</li></ul><h2>الأذونات</h2><ul><li><b>قراءة الصور</b>: للصور التي تختارها فقط</li><li><b>كتابة الصور</b>: نسخة جديدة، الأصل لا يتغير</li></ul><h2>اتصل بنا</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["es"] = `<h1>MosaicMagic — Política de Privacidad</h1><p class="date">Actualizado: 5 octubre 2026</p><h2>Resumen <span class="badge green">100% sin conexión</span> <span class="badge blue">Sin anuncios</span></h2><p>MosaicMagic es una herramienta de privacidad totalmente offline. <b style="color:#2e7d32">No recopilamos, almacenamos ni subimos</b> datos.</p><h2>Compromiso Sin Anuncios</h2><p><b style="color:#1565c0">Esta app es permanentemente sin anuncios.</b> Sin anuncios, sin pop-ups, sin notificaciones push. No integramos SDKs publicitarios ni enviamos mensajes de marketing. Nuestro único ingreso es la compra única.</p><h2>Qué Recopilamos</h2><p><b style="color:#2e7d32">Nada.</b> Cero red. Cero SDK. Cero recopilación.</p><h2>Procesamiento</h2><ul><li>Todo en tu dispositivo</li><li>Resultados solo en tu dispositivo</li><li>Exportación elimina EXIF/GPS</li></ul><h2>Permisos</h2><ul><li><b>Lectura Fotos</b>: Solo las que eliges</li><li><b>Escritura Fotos</b>: Copia nueva, originales intactos</li></ul><h2>Contacto</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["it"] = `<h1>MosaicMagic — Informativa Privacy</h1><p class="date">Aggiornato: 5 ottobre 2026</p><h2>Panoramica <span class="badge green">100% Offline</span> <span class="badge blue">Senza pubblicità</span></h2><p>MosaicMagic è uno strumento privacy completamente offline. <b style="color:#2e7d32">Non raccogliamo, memorizziamo o carichiamo</b> dati.</p><h2>Impegno Senza Pubblicità</h2><p><b style="color:#1565c0">Questa app è permanentemente senza pubblicità.</b> Nessun annuncio, nessun pop-up, nessuna notifica push. Zero SDK pubblicitari, zero messaggi di marketing. L'unica fonte di reddito è l'acquisto una tantum.</p><h2>Cosa Raccogliamo</h2><p><b style="color:#2e7d32">Nulla.</b> Zero rete. Zero SDK. Zero raccolta.</p><h2>Elaborazione</h2><ul><li>Tutto locale</li><li>Risultati solo sul dispositivo</li><li>Export rimuove EXIF/GPS</li></ul><h2>Permessi</h2><ul><li><b>Lettura Foto</b>: Solo quelle scelte</li><li><b>Scrittura Foto</b>: Nuova copia, originali intatti</li></ul><h2>Contatti</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["fr"] = `<h1>MosaicMagic — Confidentialité</h1><p class="date">Mis à jour : 5 octobre 2026</p><h2>Aperçu <span class="badge green">100% Hors ligne</span> <span class="badge blue">Sans publicité</span></h2><p>MosaicMagic est un outil de confidentialité entièrement hors ligne. <b style="color:#2e7d32">Nous ne collectons, stockons ni téléchargeons</b> aucune donnée.</p><h2>Engagement Sans Publicité</h2><p><b style="color:#1565c0">Cette app est définitivement sans publicité.</b> Pas de publicité, pas de pop-ups, pas de notifications push. Aucun SDK publicitaire, aucun message marketing. Notre seule source de revenus est l'achat unique.</p><h2>Ce que Nous Collectons</h2><p><b style="color:#2e7d32">Rien.</b> Zéro réseau. Zéro SDK. Zéro collecte.</p><h2>Traitement</h2><ul><li>Tout sur votre appareil</li><li>Résultats uniquement sur l'appareil</li><li>Export supprime EXIF/GPS</li></ul><h2>Autorisations</h2><ul><li><b>Lecture Photos</b> : Uniquement vos choix</li><li><b>Écriture Photos</b> : Nouvelle copie, originaux intacts</li></ul><h2>Contact</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["ru"] = `<h1>MosaicMagic — Конфиденциальность</h1><p class="date">Обновлено: 5 октября 2026</p><h2>Обзор <span class="badge green">100% Офлайн</span> <span class="badge blue">Без рекламы</span></h2><p>MosaicMagic — полностью офлайн-инструмент. <b style="color:#2e7d32">Мы не собираем, не храним и не загружаем</b> данные.</p><h2>Обещание Без Рекламы</h2><p><b style="color:#1565c0">Это приложение навсегда без рекламы.</b> Никакой рекламы, никаких всплывающих окон, никаких push-уведомлений. Ноль рекламных SDK, ноль маркетинговых сообщений. Единственный источник дохода — разовая покупка.</p><h2>Что Собираем</h2><p><b style="color:#2e7d32">Ничего.</b> Ноль сети. Ноль SDK. Ноль сбора.</p><h2>Обработка</h2><ul><li>Всё локально</li><li>Результаты только на устройстве</li><li>Экспорт удаляет EXIF/GPS</li></ul><h2>Разрешения</h2><ul><li><b>Чтение Фото</b>: Только выбранные</li><li><b>Запись Фото</b>: Новая копия, оригиналы нетронуты</li></ul><h2>Контакты</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["de"] = `<h1>MosaicMagic — Datenschutzerklärung</h1><p class="date">Aktualisiert: 5. Oktober 2026</p><h2>Übersicht <span class="badge green">100% Offline</span> <span class="badge blue">Werbefrei</span></h2><p>MosaicMagic ist ein vollständig Offline-Tool. <b style="color:#2e7d32">Wir sammeln, speichern oder übertragen keine</b> Daten.</p><h2>Werbefreiheits-Zusagen</h2><p><b style="color:#1565c0">Diese App ist dauerhaft werbefrei.</b> Keine Werbung, keine Pop-ups, keine Push-Benachrichtigungen. Keine Werbe-SDKs, keine Marketing-Nachrichten. Unsere einzige Einnahmequelle ist der einmalige Kaufpreis.</p><h2>Was Wir Sammeln</h2><p><b style="color:#2e7d32">Nichts.</b> Keine Netzwerk. Keine SDK. Keine Datensammlung.</p><h2>Verarbeitung</h2><ul><li>Alles lokal</li><li>Ergebnisse nur auf dem Gerät</li><li>Export entfernt EXIF/GPS</li></ul><h2>Berechtigungen</h2><ul><li><b>Fotos lesen</b>: Nur deine Auswahl</li><li><b>Fotos schreiben</b>: Neue Kopie, Originale unverändert</li></ul><h2>Kontakt</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["da"] = `<h1>MosaicMagic — Privatlivspolitik</h1><p class="date">Opdateret: 5. oktober 2026</p><h2>Oversigt <span class="badge green">100% Offline</span> <span class="badge blue">Reklamefri</span></h2><p>MosaicMagic er et fuldt offline værktøj. <b style="color:#2e7d32">Vi indsamler, gemmer eller uploader ikke</b> data.</p><h2>Reklamefri Garanti</h2><p><b style="color:#1565c0">Denne app er permanent reklamefri.</b> Ingen reklamer, ingen pop-ups, ingen pushnotifikationer. Ingen reklame-SDK'er, ingen marketingbeskeder. Vores eneste indtægtskilde er det engangskøb.</p><h2>Hvad Vi Indsamler</h2><p><b style="color:#2e7d32">Intet.</b> Nul netværk. Nul SDK. Nul dataindsamling.</p><h2>Behandling</h2><ul><li>Alt lokalt</li><li>Resultater kun på enheden</li><li>Eksport fjerner EXIF/GPS</li></ul><h2>Tilladelser</h2><ul><li><b>Læs fotos</b>: Kun dit valg</li><li><b>Skriv fotos</b>: Ny kopi, originaler urørte</li></ul><h2>Kontakt</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["pt"] = `<h1>MosaicMagic — Privacidade</h1><p class="date">Atualizado: 5 outubro 2026</p><h2>Visão Geral <span class="badge green">100% Offline</span> <span class="badge blue">Sem anúncios</span></h2><p>MosaicMagic é uma ferramenta totalmente offline. <b style="color:#2e7d32">Não recolhemos, armazenamos nem enviamos</b> dados.</p><h2>Compromisso Sem Anúncios</h2><p><b style="color:#1565c0">Esta app é permanentemente sem anúncios.</b> Sem anúncios, sem pop-ups, sem notificações push. Zero SDKs publicitários, zero mensagens de marketing. A única fonte de receita é a compra única.</p><h2>O Que Recolhemos</h2><p><b style="color:#2e7d32">Nada.</b> Zero rede. Zero SDK. Zero recolha.</p><h2>Processamento</h2><ul><li>Tudo local</li><li>Resultados apenas no dispositivo</li><li>Exportação remove EXIF/GPS</li></ul><h2>Permissões</h2><ul><li><b>Ler Fotos</b>: Apenas as escolhidas</li><li><b>Escrever Fotos</b>: Nova cópia, originais intactos</li></ul><h2>Contacto</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["nb"] = `<h1>MosaicMagic — Personvern</h1><p class="date">Oppdatert: 5. oktober 2026</p><h2>Oversikt <span class="badge green">100% Offline</span> <span class="badge blue">Reklamefri</span></h2><p>MosaicMagic er et fullstendig offline verktøy. <b style="color:#2e7d32">Vi samler ikke inn, lagrer eller laster opp</b> data.</p><h2>Reklamefri Garanti</h2><p><b style="color:#1565c0">Denne appen er permanent reklamefri.</b> Ingen reklame, ingen pop-ups, ingen push-varsler. Ingen reklame-SDK, ingen markedsføringsmeldinger. Vår eneste inntektskilde er engangskjøpet.</p><h2>Hva Vi Samler</h2><p><b style="color:#2e7d32">Ingenting.</b> Null nettverk. Null SDK. Null datainnsamling.</p><h2>Behandling</h2><ul><li>Alt lokalt</li><li>Resultater kun på enheten</li><li>Eksport fjerner EXIF/GPS</li></ul><h2>Tillatelser</h2><ul><li><b>Lese bilder</b>: Kun dine valg</li><li><b>Skrive bilder</b>: Ny kopi, originaler urørt</li></ul><h2>Kontakt</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;
