// 隐私政策 — 14 语言 | 更新：2026-10-04
const POLICIES = {};

POLICIES["zh-Hans"] = `<h1>魔方马赛克 — 隐私政策</h1><p class="date">最后更新：2026年10月4日</p><h2>概述 <span class="badge green">100% 离线</span></h2><p>魔方马赛克是一款完全离线的图片隐私保护工具。我们<b style="color:#2e7d32">不收集、不存储、不上传</b>任何用户数据。</p><h2>我们收集什么</h2><p><b style="color:#2e7d32">什么都不收集。</b>零网络请求、零第三方 SDK、零数据收集。</p><h2>图片数据处理</h2><ul><li>所有识别和打码处理均在设备本地完成</li><li>处理结果仅保存在您的设备上</li><li>导出自动清除 EXIF/GPS 等元数据</li></ul><h2>权限说明</h2><ul><li><b>相册读取</b>：浏览并选择要打码的照片。仅读取您选择的照片，不扫描不上传。</li><li><b>相册写入</b>：保存打码后的图片。保存新副本，不覆盖原图。</li></ul><h2>联系我们</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["zh-Hant"] = `<h1>魔方馬賽克 — 隱私政策</h1><p class="date">最後更新：2026年10月4日</p><h2>概述 <span class="badge green">100% 離線</span></h2><p>魔方馬賽克是一款完全離線的圖片隱私保護工具。我們<b style="color:#2e7d32">不收集、不儲存、不上傳</b>任何使用者資料。</p><h2>我們收集什麼</h2><p><b style="color:#2e7d32">什麼都不收集。</b>零網路請求、零第三方 SDK、零資料收集。</p><h2>圖片處理</h2><ul><li>所有識別和打碼均在裝置本地完成</li><li>結果僅保存在裝置上</li><li>匯出自動清除 EXIF/GPS</li></ul><h2>權限</h2><ul><li><b>相簿讀取</b>：瀏覽並選擇照片。僅讀取所選照片。</li><li><b>相簿寫入</b>：儲存處理後圖片。新副本，不覆蓋原圖。</li></ul><h2>聯絡我們</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["en"] = `<h1>MosaicMagic — Privacy Policy</h1><p class="date">Last updated: October 4, 2026</p><h2>Overview <span class="badge green">100% Offline</span></h2><p>MosaicMagic is a fully offline photo privacy tool. We <b style="color:#2e7d32">do not collect, store, or upload</b> any user data.</p><h2>What We Collect</h2><p><b style="color:#2e7d32">Nothing.</b> Zero network requests. Zero third-party SDKs. Zero data collection.</p><h2>Image Processing</h2><ul><li>All detection and censoring happens locally on your device</li><li>Results stored only on your device</li><li>Exports automatically strip EXIF/GPS metadata</li></ul><h2>Permissions</h2><ul><li><b>Photo Read</b>: Browse and select photos to censor. Only accesses photos you choose.</li><li><b>Photo Write</b>: Save censored images. Creates a new copy — originals untouched.</li></ul><h2>Contact</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["ja"] = `<h1>モザイクマジック — プライバシーポリシー</h1><p class="date">最終更新：2026年10月4日</p><h2>概要 <span class="badge green">100% オフライン</span></h2><p>モザイクマジックは完全オフラインの写真プライバシー保護ツールです。<b style="color:#2e7d32">収集・保存・アップロードは一切行いません。</b></p><h2>収集データ</h2><p><b style="color:#2e7d32">なし。</b>ネットワーク通信ゼロ、SDKゼロ、データ収集ゼロ。</p><h2>画像処理</h2><ul><li>すべて端末内で処理</li><li>結果は端末内にのみ保存</li><li>書き出し時EXIF/GPS自動削除</li></ul><h2>権限</h2><ul><li><b>写真読み取り</b>：閲覧・選択のみ</li><li><b>写真書き込み</b>：新規コピー保存、元画像不改変</li></ul><h2>お問い合わせ</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["ko"] = `<h1>모자이크 매직 — 개인정보 처리방침</h1><p class="date">최종 업데이트: 2026년 10월 4일</p><h2>개요 <span class="badge green">100% 오프라인</span></h2><p>모자이크 매직은 완전 오프라인 사진 개인정보 보호 도구입니다. <b style="color:#2e7d32">수집·저장·업로드를 하지 않습니다.</b></p><h2>수집 데이터</h2><p><b style="color:#2e7d32">없음.</b> 네트워크 요청 없음, SDK 없음, 데이터 수집 없음.</p><h2>이미지 처리</h2><ul><li>모든 처리는 기기 내에서 수행</li><li>결과는 기기에만 저장</li><li>내보낼 때 EXIF/GPS 자동 삭제</li></ul><h2>권한</h2><ul><li><b>사진 읽기</b>: 선택한 사진만 접근</li><li><b>사진 쓰기</b>: 새 복사본 저장, 원본 수정 안 함</li></ul><h2>연락처</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["ar"] = `<h1>موزاييك ماجيك — سياسة الخصوصية</h1><p class="date">آخر تحديث: 4 أكتوبر 2026</p><h2>نظرة عامة <span class="badge green">100% دون اتصال</span></h2><p>موزاييك ماجيك أداة حماية خصوصية الصور تعمل دون اتصال. <b style="color:#2e7d32">لا نجمع أو نخزن أو نرفع</b> أي بيانات.</p><h2>ما نجمعه</h2><p><b style="color:#2e7d32">لا شيء.</b> صفر طلبات شبكة، صفر SDK، صفر جمع بيانات.</p><h2>معالجة الصور</h2><ul><li>جميع المعالجة على جهازك</li><li>النتائج على جهازك فقط</li><li>حذف تلقائي لـ EXIF/GPS</li></ul><h2>الأذونات</h2><ul><li><b>قراءة الصور</b>: للصور التي تختارها فقط</li><li><b>كتابة الصور</b>: نسخة جديدة، الأصل لا يتغير</li></ul><h2>اتصل بنا</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["es"] = `<h1>MosaicMagic — Política de Privacidad</h1><p class="date">Actualizado: 4 octubre 2026</p><h2>Resumen <span class="badge green">100% sin conexión</span></h2><p>MosaicMagic es una herramienta de privacidad totalmente offline. <b style="color:#2e7d32">No recopilamos, almacenamos ni subimos</b> datos.</p><h2>Qué Recopilamos</h2><p><b style="color:#2e7d32">Nada.</b> Cero red. Cero SDK. Cero recopilación.</p><h2>Procesamiento</h2><ul><li>Todo se procesa en tu dispositivo</li><li>Resultados solo en tu dispositivo</li><li>Exportación elimina EXIF/GPS automáticamente</li></ul><h2>Permisos</h2><ul><li><b>Lectura Fotos</b>: Solo las que eliges</li><li><b>Escritura Fotos</b>: Copia nueva, originales intactos</li></ul><h2>Contacto</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["it"] = `<h1>MosaicMagic — Informativa Privacy</h1><p class="date">Aggiornato: 4 ottobre 2026</p><h2>Panoramica <span class="badge green">100% Offline</span></h2><p>MosaicMagic è uno strumento privacy completamente offline. <b style="color:#2e7d32">Non raccogliamo, memorizziamo o carichiamo</b> dati.</p><h2>Cosa Raccogliamo</h2><p><b style="color:#2e7d32">Nulla.</b> Zero rete. Zero SDK. Zero raccolta.</p><h2>Elaborazione</h2><ul><li>Tutto locale sul dispositivo</li><li>Risultati solo sul dispositivo</li><li>Export rimuove EXIF/GPS automaticamente</li></ul><h2>Permessi</h2><ul><li><b>Lettura Foto</b>: Solo quelle scelte</li><li><b>Scrittura Foto</b>: Nuova copia, originali intatti</li></ul><h2>Contatti</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["fr"] = `<h1>MosaicMagic — Confidentialité</h1><p class="date">Mis à jour : 4 octobre 2026</p><h2>Aperçu <span class="badge green">100% Hors ligne</span></h2><p>MosaicMagic est un outil de confidentialité entièrement hors ligne. <b style="color:#2e7d32">Nous ne collectons, stockons ni téléchargeons</b> aucune donnée.</p><h2>Ce que Nous Collectons</h2><p><b style="color:#2e7d32">Rien.</b> Zéro réseau. Zéro SDK. Zéro collecte.</p><h2>Traitement</h2><ul><li>Tout sur votre appareil</li><li>Résultats uniquement sur l'appareil</li><li>Export supprime EXIF/GPS automatiquement</li></ul><h2>Autorisations</h2><ul><li><b>Lecture Photos</b> : Uniquement vos choix</li><li><b>Écriture Photos</b> : Nouvelle copie, originaux intacts</li></ul><h2>Contact</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["ru"] = `<h1>MosaicMagic — Конфиденциальность</h1><p class="date">Обновлено: 4 октября 2026</p><h2>Обзор <span class="badge green">100% Офлайн</span></h2><p>MosaicMagic — полностью офлайн-инструмент. <b style="color:#2e7d32">Мы не собираем, не храним и не загружаем</b> данные.</p><h2>Что Собираем</h2><p><b style="color:#2e7d32">Ничего.</b> Ноль сети. Ноль SDK. Ноль сбора.</p><h2>Обработка</h2><ul><li>Всё локально на устройстве</li><li>Результаты только на устройстве</li><li>Экспорт удаляет EXIF/GPS автоматически</li></ul><h2>Разрешения</h2><ul><li><b>Чтение Фото</b>: Только выбранные вами</li><li><b>Запись Фото</b>: Новая копия, оригиналы нетронуты</li></ul><h2>Контакты</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["de"] = `<h1>MosaicMagic — Datenschutzerklärung</h1><p class="date">Aktualisiert: 4. Oktober 2026</p><h2>Übersicht <span class="badge green">100% Offline</span></h2><p>MosaicMagic ist ein vollständig Offline-Tool. <b style="color:#2e7d32">Wir sammeln, speichern oder übertragen keine</b> Daten.</p><h2>Was Wir Sammeln</h2><p><b style="color:#2e7d32">Nichts.</b> Keine Netzwerk. Keine SDK. Keine Datensammlung.</p><h2>Verarbeitung</h2><ul><li>Alles lokal auf dem Gerät</li><li>Ergebnisse nur auf dem Gerät</li><li>Export entfernt EXIF/GPS automatisch</li></ul><h2>Berechtigungen</h2><ul><li><b>Fotos lesen</b>: Nur deine Auswahl</li><li><b>Fotos schreiben</b>: Neue Kopie, Originale unverändert</li></ul><h2>Kontakt</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["da"] = `<h1>MosaicMagic — Privatlivspolitik</h1><p class="date">Opdateret: 4. oktober 2026</p><h2>Oversigt <span class="badge green">100% Offline</span></h2><p>MosaicMagic er et fuldt offline værktøj. <b style="color:#2e7d32">Vi indsamler, gemmer eller uploader ikke</b> data.</p><h2>Hvad Vi Indsamler</h2><p><b style="color:#2e7d32">Intet.</b> Nul netværk. Nul SDK. Nul dataindsamling.</p><h2>Behandling</h2><ul><li>Alt lokalt på enheden</li><li>Resultater kun på enheden</li><li>Eksport fjerner EXIF/GPS automatisk</li></ul><h2>Tilladelser</h2><ul><li><b>Læs fotos</b>: Kun dit valg</li><li><b>Skriv fotos</b>: Ny kopi, originaler urørte</li></ul><h2>Kontakt</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["pt"] = `<h1>MosaicMagic — Privacidade</h1><p class="date">Atualizado: 4 outubro 2026</p><h2>Visão Geral <span class="badge green">100% Offline</span></h2><p>MosaicMagic é uma ferramenta totalmente offline. <b style="color:#2e7d32">Não recolhemos, armazenamos nem enviamos</b> dados.</p><h2>O Que Recolhemos</h2><p><b style="color:#2e7d32">Nada.</b> Zero rede. Zero SDK. Zero recolha.</p><h2>Processamento</h2><ul><li>Tudo local no dispositivo</li><li>Resultados apenas no dispositivo</li><li>Exportação remove EXIF/GPS automaticamente</li></ul><h2>Permissões</h2><ul><li><b>Ler Fotos</b>: Apenas as escolhidas</li><li><b>Escrever Fotos</b>: Nova cópia, originais intactos</li></ul><h2>Contacto</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;

POLICIES["nb"] = `<h1>MosaicMagic — Personvern</h1><p class="date">Oppdatert: 4. oktober 2026</p><h2>Oversikt <span class="badge green">100% Offline</span></h2><p>MosaicMagic er et fullstendig offline verktøy. <b style="color:#2e7d32">Vi samler ikke inn, lagrer eller laster opp</b> data.</p><h2>Hva Vi Samler</h2><p><b style="color:#2e7d32">Ingenting.</b> Null nettverk. Null SDK. Null datainnsamling.</p><h2>Behandling</h2><ul><li>Alt lokalt på enheten</li><li>Resultater kun på enheten</li><li>Eksport fjerner EXIF/GPS automatisk</li></ul><h2>Tillatelser</h2><ul><li><b>Lese bilder</b>: Kun dine valg</li><li><b>Skrive bilder</b>: Ny kopi, originaler urørt</li></ul><h2>Kontakt</h2><p><a class="email" href="mailto:branwayne1999@icloud.com">branwayne1999@icloud.com</a></p>`;
